=== servicecatalog/development/oscm-serviceprovisioning/javares/TechnicalServices.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="oscm.serviceprovisioning/1.9/TechnicalService.xsd"
	xmlns:tns="oscm.serviceprovisioning/1.9/TechnicalService.xsd">

	<xsd:element name="TechnicalServices">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="tns:TechnicalService" maxOccurs="unbounded"
					minOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="TechnicalService">
		<xsd:complexType>

			<xsd:sequence>
				<xsd:element name="AccessInfo" type="tns:LocalizedDescriptionType"
					maxOccurs="unbounded" minOccurs="0" />
				<xsd:element name="LocalizedDescription" type="tns:LocalizedDescriptionType"
					maxOccurs="unbounded" minOccurs="0" />
				<xsd:element name="LocalizedLicense" type="tns:LocalizedDescriptionType"
					maxOccurs="unbounded" minOccurs="0" />
				<xsd:element name="LocalizedTag" type="tns:LocalizedDescriptionType"
					maxOccurs="unbounded" minOccurs="0" />
				<xsd:element name="ParameterDefinition" type="tns:ParameterDefinitionType"
					maxOccurs="unbounded" minOccurs="0" />
				<xsd:element name="Event" type="tns:EventType"
					maxOccurs="unbounded" minOccurs="0" />
				<xsd:element name="Role" type="tns:RoleType" maxOccurs="unbounded"
					minOccurs="0" />
				<xsd:element name="Operation" type="tns:OperationType"
					minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>

			<xsd:attribute name="id" type="tns:StrId" use="required" />
			<xsd:attribute name="build" type="tns:Str255" />
			<xsd:attribute name="accessType" use="required">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="DIRECT" />
						<xsd:enumeration value="LOGIN" />
						<xsd:enumeration value="USER" />
						<xsd:enumeration value="EXTERNAL" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>

			<xsd:attribute name="provisioningType">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="ASYNCHRONOUS" />
						<xsd:enumeration value="SYNCHRONOUS" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>

			<xsd:attribute name="provisioningUrl" type="tns:Str255" />
			<xsd:attribute name="provisioningVersion" type="tns:Str255" />
			<xsd:attribute name="provisioningTimeout" type="xsd:long" />
			<xsd:attribute name="provisioningUsername" type="tns:Str255" />
			<xsd:attribute name="provisioningPassword" type="tns:Str255" />
			<xsd:attribute name="baseUrl" type="tns:Str255" />
			<xsd:attribute name="loginPath" type="tns:Str255" />
			<xsd:attribute name="onlyOneSubscriptionPerUser" type="xsd:boolean"
				default="false" />
			<xsd:attribute name="allowingOnBehalfActing" type="xsd:boolean"
				default="false" />
			<xsd:attribute name="billingIdentifier" type="tns:Str255" />
		</xsd:complexType>
	</xsd:element>

	<xsd:simpleType name="StrId">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="40" />
			<xsd:pattern
				value="[()\-.0-9@A-Z\[\]_a-&#xD7FF;&#xE000;-&#xFFFD;&#x10000;-&#x10FFFF;]+([&#x20;]*[()\-.0-9@A-Z\[\]_a-&#xD7FF;&#xE000;-&#xFFFD;&#x10000;-&#x10FFFF;])*" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="Str255">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="255" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="LocalizedDescriptionType">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="locale" type="xsd:string" />
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:complexType name="EventType">
		<xsd:sequence>
			<xsd:element name="LocalizedDescription" type="tns:LocalizedDescriptionType"
				maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="id" type="tns:StrId" use="required" />
	</xsd:complexType>

	<xsd:complexType name="RoleType">
		<xsd:sequence>
			<xsd:element name="LocalizedName" type="tns:LocalizedDescriptionType"
				maxOccurs="unbounded" minOccurs="1" />
			<xsd:element name="LocalizedDescription" type="tns:LocalizedDescriptionType"
				maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="id" type="tns:StrId" use="required" />
	</xsd:complexType>

	<xsd:complexType name="ParameterDefinitionType">
		<xsd:sequence>
			<xsd:element name="Options" type="tns:OptionsType"
				maxOccurs="1" minOccurs="0" />
			<xsd:element name="LocalizedDescription" type="tns:LocalizedDescriptionType"
				maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="id" type="tns:StrId" use="required" />
		<xsd:attribute name="mandatory" type="xsd:boolean" use="optional" />
		<xsd:attribute name="configurable" type="xsd:boolean"
			use="optional" />
		<xsd:attribute name="default" type="xsd:string" use="optional" />
		<xsd:attribute name="minValue" type="xsd:long" use="optional" />
		<xsd:attribute name="maxValue" type="xsd:long" use="optional" />
		<xsd:attribute name="valueType" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="BOOLEAN" />
					<xsd:enumeration value="INTEGER" />
					<xsd:enumeration value="LONG" />
					<xsd:enumeration value="STRING" />
					<xsd:enumeration value="ENUMERATION" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="modificationType" use="optional"
			default="STANDARD">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="STANDARD" />
					<xsd:enumeration value="ONE_TIME" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="OptionsType">
		<xsd:sequence>
			<xsd:element name="Option" type="tns:OptionType"
				maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="OptionType">
		<xsd:sequence>
			<xsd:element name="LocalizedOption" type="tns:LocalizedDescriptionType"
				maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="id" type="tns:StrId" use="required" />
	</xsd:complexType>

	<xsd:complexType name="OperationType">
		<xsd:sequence>
			<xsd:element name="LocalizedName" type="tns:LocalizedDescriptionType"
				minOccurs="1" maxOccurs="unbounded" />
			<xsd:element name="LocalizedDescription" type="tns:LocalizedDescriptionType"
				maxOccurs="unbounded" minOccurs="1" />
			<xsd:element name="OperationParameter" type="tns:OperationParameterType"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="id" type="tns:StrId" use="required" />
		<xsd:attribute name="actionURL" type="tns:Str255" use="required" />
	</xsd:complexType>

	<xsd:complexType name="OperationParameterType">
		<xsd:sequence>
			<xsd:element name="LocalizedName" type="tns:LocalizedDescriptionType"
				minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="id" type="tns:StrId" use="required" />
		<xsd:attribute name="type" type="tns:OperationParameterTypeType"
			use="required" />
		<xsd:attribute name="mandatory" type="xsd:boolean"
			default="false" />
	</xsd:complexType>

	<xsd:simpleType name="OperationParameterTypeType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="INPUT_STRING" />
			<xsd:enumeration value="REQUEST_SELECT" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="CustomTabName">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="locale" type="xsd:string" />
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:complexType name="CustomTabUrl">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="locale" type="xsd:string" />
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

</xsd:schema>

=== servicecatalog/development/oscm-app-openstack/resources/TechnicalService_OpenStack.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright FUJITSU LIMITED 2017-->

<tns:TechnicalServices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xsi:schemaLocation="oscm.serviceprovisioning/1.9/TechnicalService.xsd ../../oscm-serviceprovisioning/javares/TechnicalServices.xsd"
                       xmlns:tns="oscm.serviceprovisioning/1.9/TechnicalService.xsd">
  <tns:TechnicalService accessType="DIRECT" allowingOnBehalfActing="false" baseUrl=""
                        build="20140708" id="OPENSTACK_V4" loginPath=""
                        onlyOneSubscriptionPerUser="false" provisioningType="ASYNCHRONOUS"
                        provisioningUrl="http://oscm-app:8880/oscm-app/webservices/oscm-app/oscm-app/org.oscm.app.v2_0.service.AsynchronousProvisioningProxy?wsdl"
                        provisioningVersion="1.0">
    <AccessInfo locale="en" >OpenStack Access Info</AccessInfo>
    <LocalizedDescription locale="en">OpenStack IaaS implementation</LocalizedDescription>
    <LocalizedLicense locale="en" />
    <LocalizedTag locale="en">OpenStack</LocalizedTag>
    <ParameterDefinition configurable="false" default="ess.openstack" id="APP_CONTROLLER_ID" mandatory="true"
                         valueType="STRING">
      <LocalizedDescription locale="en">ID of the controller implementation</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition configurable="true" id="STACK_NAME" default="" mandatory="true" valueType="STRING" modificationType="ONE_TIME">
      <LocalizedDescription locale="en">OpenStack instance name</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition configurable="true" default="([A-Za-z][A-Za-z0-9_-]*){1,30}" id="STACK_NAME_PATTERN"
                         modificationType="ONE_TIME" mandatory="true" valueType="STRING">
      <LocalizedDescription locale="en">Validation pattern for the stack name (regex)</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition configurable="true" id="TEMPLATE_NAME" default="template.json" mandatory="true"
                         valueType="ENUMERATION" modificationType="ONE_TIME">
      <Options>
        <Option id="template.json">
          <LocalizedOption locale="en">template.json</LocalizedOption>
        </Option>
        <Option id="template.yaml">
          <LocalizedOption locale="en">template.yaml</LocalizedOption>
        </Option>
      </Options>
      <LocalizedDescription locale="en">Template files for resource orchestration</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition configurable="true" id="TENANT_ID" default="<your.tenant.id>" mandatory="true" valueType="STRING" modificationType="ONE_TIME">
      <LocalizedDescription locale="en">Tenant ID (project ID)</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition configurable="true" id="ACCESS_INFO_PATTERN" default="Key pair name: {KP_Out}; Assigned network addresses: {NW_Out};" mandatory="true" valueType="STRING" modificationType="ONE_TIME">
      <LocalizedDescription locale="en">Pattern for access information</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition configurable="true" id="TP_ImageId" default="cedarish" mandatory="true" valueType="STRING" modificationType="ONE_TIME">
      <LocalizedDescription locale="en">Image ID</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition configurable="true" id="TP_flavor" default="m1.small" mandatory="true"
                         valueType="STRING" modificationType="ONE_TIME">
      <LocalizedDescription locale="en">Instance type (flavor)</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition configurable="true" id="TP_KeyName" default="openstackkeypair" mandatory="true" valueType="STRING" modificationType="ONE_TIME">
      <LocalizedDescription locale="en">Key name</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition configurable="true" id="TP_az" default="nova" mandatory="true"
                         valueType="STRING" modificationType="ONE_TIME">
      <LocalizedDescription locale="en">Availability zone</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition configurable="true" id="TP_VmName" mandatory="true" modificationType="ONE_TIME" valueType="STRING">
      <LocalizedDescription locale="en">VmName</LocalizedDescription>
      <LocalizedDescription locale="de"/>
      <LocalizedDescription locale="ja"/>
    </ParameterDefinition>
    <ParameterDefinition configurable="true" id="TP_AdminPassword" mandatory="true" modificationType="ONE_TIME" valueType="STRING">
      <LocalizedDescription locale="en">AdminPassword</LocalizedDescription>
      <LocalizedDescription locale="de"/>
      <LocalizedDescription locale="ja"/>
    </ParameterDefinition>
    <ParameterDefinition configurable="true" id="TP_PrivateNetworkId" mandatory="true" modificationType="ONE_TIME" valueType="STRING">
      <LocalizedDescription locale="en">PrivateNetworkId</LocalizedDescription>
      <LocalizedDescription locale="de"/>
      <LocalizedDescription locale="ja"/>
    </ParameterDefinition>
    <ParameterDefinition configurable="true" id="TP_SubnetId" mandatory="true" modificationType="ONE_TIME" valueType="STRING">
      <LocalizedDescription locale="en">SubnetId</LocalizedDescription>
      <LocalizedDescription locale="de"/>
      <LocalizedDescription locale="ja"/>
    </ParameterDefinition>
    <ParameterDefinition configurable="true" id="TP_PublicNetworkId" mandatory="true" modificationType="ONE_TIME" valueType="STRING">
      <LocalizedDescription locale="en">PublicNetworkId</LocalizedDescription>
      <LocalizedDescription locale="de"/>
      <LocalizedDescription locale="ja"/>
    </ParameterDefinition>
    <ParameterDefinition configurable="true" id="TP_ARRAY_SecurityGroupName" mandatory="true" modificationType="ONE_TIME" valueType="STRING">
      <LocalizedDescription locale="en">SecurityGroupName</LocalizedDescription>
      <LocalizedDescription locale="de"/>
      <LocalizedDescription locale="ja"/>
    </ParameterDefinition>
    <ParameterDefinition configurable="true" id="MAIL_FOR_COMPLETION" default=""
                         mandatory="false" valueType="STRING" modificationType="ONE_TIME">
      <LocalizedDescription locale="en">The address to which emails are to be sent that describe manual steps required to complete an operation. If you specify this parameter, the service controller interrupts the processing of each operation before its completion and waits for a notification about the execution of a manual action. Omit this parameter if you do not want to interrupt the processing.</LocalizedDescription>
      <LocalizedDescription locale="ja">操作を完了するために手動の手順が必要であることを知らせるemailの送信先メールアドレス。このパラメーターを指定すると、サービスコントロールは各操作の完了前に処理を中断して、手動の操作が終わったことを知らせる通知が届くまで待ちます。処理を中断したくない場合は、このパラメーターを省略してください。</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition configurable="false" default="0" id="VMS_NUMBER"
                         mandatory="true" valueType="LONG">
      <LocalizedDescription locale="en">The number of VMs of IaaS subscriptions</LocalizedDescription>
    </ParameterDefinition>
    <Operation actionURL="http://oscm-app:8880/oscm-app/webservices/oscm-app/oscm-app/org.oscm.app.v2_0.service.AsynchronousOperationProxy?wsdl" id="START_VIRTUAL_SYSTEM">
      <LocalizedName locale="de">Start</LocalizedName>
      <LocalizedName locale="en">Start</LocalizedName>
      <LocalizedName locale="ja">起動</LocalizedName>
      <LocalizedDescription locale="de">Startet alle Server</LocalizedDescription>
      <LocalizedDescription locale="en">Start all servers</LocalizedDescription>
      <LocalizedDescription locale="ja">システムを起動します</LocalizedDescription>
    </Operation>
    <Operation actionURL="http://oscm-app:8880/oscm-app/webservices/oscm-app/oscm-app/org.oscm.app.v2_0.service.AsynchronousOperationProxy?wsdl" id="STOP_VIRTUAL_SYSTEM">
      <LocalizedName locale="de">Stop</LocalizedName>
      <LocalizedName locale="en">Stop</LocalizedName>
      <LocalizedName locale="ja">停止</LocalizedName>
      <LocalizedDescription locale="de">Stoppt alle Server</LocalizedDescription>
      <LocalizedDescription locale="en">Stop all servers</LocalizedDescription>
      <LocalizedDescription locale="ja">システムを停止します</LocalizedDescription>
    </Operation>
    <Operation actionURL="http://oscm-app:8880/oscm-app/webservices/oscm-app/oscm-app/org.oscm.app.v2_0.service.AsynchronousOperationProxy?wsdl" id="RESUME_VIRTUAL_SYSTEM">
      <LocalizedName locale="de">Fortsetzen</LocalizedName>
      <LocalizedName locale="en">Resume</LocalizedName>
      <LocalizedName locale="ja">レジューム</LocalizedName>
      <LocalizedDescription locale="de">Setzt den Betrieb der Instanz fort</LocalizedDescription>
      <LocalizedDescription locale="en">Resume the instance</LocalizedDescription>
      <LocalizedDescription locale="ja">システムをレジュームします</LocalizedDescription>
    </Operation>
    <Operation actionURL="http://oscm-app:8880/oscm-app/webservices/oscm-app/oscm-app/org.oscm.app.v2_0.service.AsynchronousOperationProxy?wsdl" id="SUSPEND_VIRTUAL_SYSTEM">
      <LocalizedName locale="de">Aussetzen</LocalizedName>
      <LocalizedName locale="en">Suspend</LocalizedName>
      <LocalizedName locale="ja">サスペンド</LocalizedName>
      <LocalizedDescription locale="de">Setzt die Instanz aus</LocalizedDescription>
      <LocalizedDescription locale="en">Suspend the instance</LocalizedDescription>
      <LocalizedDescription locale="ja">システムをサスペンドします</LocalizedDescription>
    </Operation>
  </tns:TechnicalService>
</tns:TechnicalServices>

=== servicecatalog/development/oscm-app-iaas/VMware_TechnicalServices_old.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright FUJITSU LIMITED 2017-->
 
<tns:TechnicalServices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="oscm.serviceprovisioning/1.9/TechnicalService.xsd ../../oscm-serviceprovisioning/javares/TechnicalServices.xsd"
  xmlns:tns="oscm.serviceprovisioning/1.9/TechnicalService.xsd">
  <tns:TechnicalService accessType="DIRECT" allowingOnBehalfActing="false" baseUrl="not_required"
    build="08.08.2012" id="VMware" loginPath="/Dynamically provided by the IaaS-system" onlyOneSubscriptionPerUser="false"
    provisioningType="ASYNCHRONOUS" provisioningUrl="http://127.0.0.1:8080/ProvisioningService/ProvisioningServiceProxyBean?wsdl"
    provisioningVersion="1.0">
    <AccessInfo locale="en" >VMware Access Info.</AccessInfo>
    <LocalizedDescription locale="de">VMware IaaS Implementierung.</LocalizedDescription>
    <LocalizedDescription locale="en">VMware IaaS implementation.</LocalizedDescription>
    <LocalizedLicense locale="en" />
    <LocalizedTag locale="en">virtual server</LocalizedTag>
    <LocalizedTag locale="en">linux</LocalizedTag>
    <LocalizedTag locale="en">windows 7</LocalizedTag>
    <LocalizedTag locale="en">centos</LocalizedTag>
    <ParameterDefinition configurable="true" default="estess([a-z0-9]){6,8}" id="VMW_INSTANCENAME_PATTERN"
      mandatory="true" valueType="STRING">
      <LocalizedDescription locale="en">Validation pattern for instance name (regex)</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition configurable="true" default="estess" id="VMW_INSTANCENAME_PREFIX"
      mandatory="false" valueType="STRING">
      <LocalizedDescription locale="en">Automatic prepended prefix for the instance name</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition configurable="true" id="VMW_INSTANCENAME" mandatory="true" valueType="STRING">
      <LocalizedDescription locale="de">Name der Instanz</LocalizedDescription>
      <LocalizedDescription locale="en">Instance name</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition configurable="true" default="centos6x64tpl" id="VMW_TEMPLATENAME"
      mandatory="true" valueType="STRING">
      <LocalizedDescription locale="de">Name des VMware-Templates</LocalizedDescription>
      <LocalizedDescription locale="en">VMware template name</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition configurable="true" id="VMW_INSTANCEPARAM" mandatory="false" valueType="STRING">
      <LocalizedDescription locale="de">VMware Konfigurationsparameter</LocalizedDescription>
      <LocalizedDescription locale="en">VMware configuration parameters</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition configurable="true" id="VMW_MAIL_FOR_COMPLETION" mandatory="false"
      valueType="STRING">
      <LocalizedDescription locale="en">Defines whether manual steps are required before activation the
        deployment for the customer.</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition configurable="true" default="1" id="VMW_CPU" mandatory="true" valueType="ENUMERATION">
      <Options>
        <Option id="1">
          <LocalizedOption locale="en">1</LocalizedOption>
        </Option>
        <Option id="2">
          <LocalizedOption locale="en">2</LocalizedOption>
        </Option>
        <Option id="3">
          <LocalizedOption locale="en">3</LocalizedOption>
        </Option>
        <Option id="4">
          <LocalizedOption locale="en">4</LocalizedOption>
        </Option>
      </Options>
      <LocalizedDescription locale="de">Anzahl CPUs</LocalizedDescription>
      <LocalizedDescription locale="en">Number of CPUs</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition configurable="true" default="512" id="VMW_RAM" mandatory="true" valueType="ENUMERATION">
      <Options>
        <Option id="256">
          <LocalizedOption locale="en">256 MB</LocalizedOption>
        </Option>
        <Option id="512">
          <LocalizedOption locale="en">512 MB</LocalizedOption>
        </Option>
        <Option id="1024">
          <LocalizedOption locale="en">1 GB</LocalizedOption>
        </Option>
        <Option id="2048">
          <LocalizedOption locale="en">2 GB</LocalizedOption>
        </Option>
        <Option id="3072">
          <LocalizedOption locale="en">3 GB</LocalizedOption>
        </Option>
        <Option id="4096">
          <LocalizedOption locale="en">4 GB</LocalizedOption>
        </Option>
      </Options>
      <LocalizedDescription locale="de">RAM size</LocalizedDescription>
      <LocalizedDescription locale="en">RAM-Groesse</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition configurable="false" default="11000" id="IAASPROXY_BSS_USER" mandatory="true"
      valueType="STRING">
      <LocalizedDescription locale="en">The user key to be used for service calls to BSS.</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition configurable="false" default="et62i8wof9ah" id="IAASPROXY_BSS_USER_PWD"
      mandatory="true" valueType="STRING">
      <LocalizedDescription locale="en">The password of the user to be used for service calls to BSS</LocalizedDescription>
    </ParameterDefinition>
  </tns:TechnicalService>
</tns:TechnicalServices>

=== servicecatalog/development/oscm-portal-webtests/tests/data/TechnicalServices-empty-locales.xml
<?xml version='1.0' encoding='UTF-8'?>
<!-- Copyright FUJITSU LIMITED 2016-->
 
<tns:TechnicalServices 
  xmlns:tns="oscm.serviceprovisioning/1.9/TechnicalService.xsd" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="oscm.serviceprovisioning/1.9/TechnicalService.xsd ../../oscm-serviceprovisioning/javares/TechnicalServices.xsd">

  <tns:TechnicalService id="EmptyLocales" build="23.10.2009"
    provisioningType="SYNCHRONOUS"
    provisioningUrl="@techService.http.baseurl@/example-service/services/ProvisioningService?wsdl"
    provisioningVersion="1.0"
    accessType="LOGIN" 
    baseUrl="@techService.http.baseurl@/example-service" 
    loginPath="/login"
    >
    <LocalizedDescription>TestLocalizedDescription</LocalizedDescription>
    <LocalizedLicense>TestLocalizedLicense</LocalizedLicense>
    <ParameterDefinition id="MEMORY_STORAGE" valueType="ENUMERATION" default="1">
             <Options>           
               <Option id="1">
                    <LocalizedOption>TestLocalizedOption</LocalizedOption>
               </Option>            
             </Options>
             <LocalizedDescription locale="en">new Incremental memory storage </LocalizedDescription>
    </ParameterDefinition>

    <Role id="GUEST">
      <LocalizedName>TestLocalizedName</LocalizedName>
      <LocalizedDescription locale="en">new Guests only have limited read access.</LocalizedDescription>
    </Role>
  </tns:TechnicalService>

</tns:TechnicalServices>

=== servicecatalog/development/oscm-portal-webtests/tests/data/TechnicalServices-LOGIN.xml
<?xml version='1.0' encoding='UTF-8'?>
<!-- Copyright FUJITSU LIMITED 2017-->
 
<tns:TechnicalServices xmlns:tns="oscm.serviceprovisioning/1.9/TechnicalService.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="oscm.serviceprovisioning/1.9/TechnicalService.xsd ../../oscm-serviceprovisioning/javares/TechnicalServices.xsd">
  <tns:TechnicalService id="Example 1.00" build="18.11.2010" provisioningType="SYNCHRONOUS"
    provisioningUrl="@techService.https.baseurl@/oscm-integrationtests-mockproduct/ProvisioningService?wsdl"
    provisioningVersion="1.0" provisioningUsername="admin" provisioningPassword="adminadmin" accessType="LOGIN"
    baseUrl="@techService.http.baseurl@/oscm-integrationtests-mockproduct" loginPath="/login">
    <LocalizedDescription locale="en">Just a mock service.</LocalizedDescription>
    <LocalizedLicense locale="en">THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
      IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
      MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALLMOCK INC. BE LIABLE FOR ANY
      DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
      PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
      CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
      OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.</LocalizedLicense>
    <ParameterDefinition id="MEMORY_STORAGE" valueType="ENUMERATION" default="2">
      <Options>
        <Option id="1">
          <LocalizedOption locale="en">Minimum Storage (1GB)</LocalizedOption>
        </Option>
        <Option id="2">
          <LocalizedOption locale="en">Optimum storage (2GB)</LocalizedOption>
        </Option>
        <Option id="3">
          <LocalizedOption locale="en">Maximum storage (4GB)</LocalizedOption>
        </Option>
      </Options>
      <LocalizedDescription locale="en">Incremental memory storage </LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition id="DISK_SPACE" valueType="ENUMERATION">
      <Options>
        <Option id="1">
          <LocalizedOption locale="en">Minimum Storage (100GB)</LocalizedOption>
        </Option>
        <Option id="2">
          <LocalizedOption locale="en">Optimum storage (200GB)</LocalizedOption>
        </Option>
        <Option id="3">
          <LocalizedOption locale="en">Maximum storage (400GB)</LocalizedOption>
        </Option>
      </Options>
      <LocalizedDescription locale="en">Incremental disk storage</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition id="MAX_FOLDER_NUMBER2" valueType="INTEGER" mandatory="true" configurable="true"
      minValue="12" maxValue="500" default="200">
      <LocalizedDescription locale="en"> Number2 of folders that can be created.</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition id="STRING_DATA_TYPE" valueType="STRING" mandatory="false" configurable="true"
      default="">
      <LocalizedDescription locale="en"> Number2 of folders that can be created.</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition id="MAX_FILE_NUMBER" valueType="INTEGER" mandatory="false" configurable="true"
      minValue="12" maxValue="500" default="200">
      <LocalizedDescription locale="en">Number of files that can be uploaded.</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition id="MAX_FOLDER_NUMBER" valueType="INTEGER" mandatory="false" configurable="true"
      minValue="12" maxValue="500" default="200">
      <LocalizedDescription locale="en">Number of folders that can be created.</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition id="NON_CONFIGURABLE" valueType="INTEGER" mandatory="false" configurable="false"
      minValue="12" maxValue="500" default="200">
      <LocalizedDescription locale="en">Cannot be configured</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition id="RENAME_FOLDER" valueType="BOOLEAN" default="true">
      <LocalizedDescription locale="en">Rename any user folder</LocalizedDescription>
    </ParameterDefinition>
    <ParameterDefinition id="WS_SLEEP" valueType="INTEGER" mandatory="false" minValue="0" maxValue="1200000"
      default="0">
      <LocalizedDescription locale="en"> Defines the time interval to wait befor an outgoing webservice
        of ProvisioningService.createUsers call will be executed. </LocalizedDescription>
    </ParameterDefinition>
  </tns:TechnicalService>
</tns:TechnicalServices>
