=== servicecatalog/development/oscm-serviceprovisioning/javares/TechnicalServices.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="oscm.serviceprovisioning/1.9/TechnicalService.xsd"
	xmlns:tns="oscm.serviceprovisioning/1.9/TechnicalService.xsd">

	<xsd:element name="TechnicalServices">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="tns:TechnicalService" maxOccurs="unbounded"
					minOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="TechnicalService">
		<xsd:complexType>

			<xsd:sequence>
				<xsd:element name="AccessInfo" type="tns:LocalizedDescriptionType"
					maxOccurs="unbounded" minOccurs="0" />
				<xsd:element name="LocalizedDescription" type="tns:LocalizedDescriptionType"
					maxOccurs="unbounded" minOccurs="0" />
				<xsd:element name="LocalizedLicense" type="tns:LocalizedDescriptionType"
					maxOccurs="unbounded" minOccurs="0" />
				<xsd:element name="LocalizedTag" type="tns:LocalizedDescriptionType"
					maxOccurs="unbounded" minOccurs="0" />
				<xsd:element name="ParameterDefinition" type="tns:ParameterDefinitionType"
					maxOccurs="unbounded" minOccurs="0" />
				<xsd:element name="Event" type="tns:EventType"
					maxOccurs="unbounded" minOccurs="0" />
				<xsd:element name="Role" type="tns:RoleType" maxOccurs="unbounded"
					minOccurs="0" />
				<xsd:element name="Operation" type="tns:OperationType"
					minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>

			<xsd:attribute name="id" type="tns:StrId" use="required" />
			<xsd:attribute name="build" type="tns:Str255" />
			<xsd:attribute name="accessType" use="required">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="DIRECT" />
						<xsd:enumeration value="LOGIN" />
						<xsd:enumeration value="USER" />
						<xsd:enumeration value="EXTERNAL" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>

			<xsd:attribute name="provisioningType">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="ASYNCHRONOUS" />
						<xsd:enumeration value="SYNCHRONOUS" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>

			<xsd:attribute name="provisioningUrl" type="tns:Str255" />
			<xsd:attribute name="provisioningVersion" type="tns:Str255" />
			<xsd:attribute name="provisioningTimeout" type="xsd:long" />
			<xsd:attribute name="provisioningUsername" type="tns:Str255" />
			<xsd:attribute name="provisioningPassword" type="tns:Str255" />
			<xsd:attribute name="baseUrl" type="tns:Str255" />
			<xsd:attribute name="loginPath" type="tns:Str255" />
			<xsd:attribute name="onlyOneSubscriptionPerUser" type="xsd:boolean"
				default="false" />
			<xsd:attribute name="allowingOnBehalfActing" type="xsd:boolean"
				default="false" />
			<xsd:attribute name="billingIdentifier" type="tns:Str255" />
		</xsd:complexType>
	</xsd:element>

	<xsd:simpleType name="StrId">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="40" />
			<xsd:pattern
				value="[()\-.0-9@A-Z\[\]_a-&#xD7FF;&#xE000;-&#xFFFD;&#x10000;-&#x10FFFF;]+([&#x20;]*[()\-.0-9@A-Z\[\]_a-&#xD7FF;&#xE000;-&#xFFFD;&#x10000;-&#x10FFFF;])*" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="Str255">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="255" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="LocalizedDescriptionType">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="locale" type="xsd:string" />
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:complexType name="EventType">
		<xsd:sequence>
			<xsd:element name="LocalizedDescription" type="tns:LocalizedDescriptionType"
				maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="id" type="tns:StrId" use="required" />
	</xsd:complexType>

	<xsd:complexType name="RoleType">
		<xsd:sequence>
			<xsd:element name="LocalizedName" type="tns:LocalizedDescriptionType"
				maxOccurs="unbounded" minOccurs="1" />
			<xsd:element name="LocalizedDescription" type="tns:LocalizedDescriptionType"
				maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="id" type="tns:StrId" use="required" />
	</xsd:complexType>

	<xsd:complexType name="ParameterDefinitionType">
		<xsd:sequence>
			<xsd:element name="Options" type="tns:OptionsType"
				maxOccurs="1" minOccurs="0" />
			<xsd:element name="LocalizedDescription" type="tns:LocalizedDescriptionType"
				maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="id" type="tns:StrId" use="required" />
		<xsd:attribute name="mandatory" type="xsd:boolean" use="optional" />
		<xsd:attribute name="configurable" type="xsd:boolean"
			use="optional" />
		<xsd:attribute name="default" type="xsd:string" use="optional" />
		<xsd:attribute name="minValue" type="xsd:long" use="optional" />
		<xsd:attribute name="maxValue" type="xsd:long" use="optional" />
		<xsd:attribute name="valueType" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="BOOLEAN" />
					<xsd:enumeration value="INTEGER" />
					<xsd:enumeration value="LONG" />
					<xsd:enumeration value="STRING" />
					<xsd:enumeration value="ENUMERATION" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="modificationType" use="optional"
			default="STANDARD">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="STANDARD" />
					<xsd:enumeration value="ONE_TIME" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="OptionsType">
		<xsd:sequence>
			<xsd:element name="Option" type="tns:OptionType"
				maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="OptionType">
		<xsd:sequence>
			<xsd:element name="LocalizedOption" type="tns:LocalizedDescriptionType"
				maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="id" type="tns:StrId" use="required" />
	</xsd:complexType>

	<xsd:complexType name="OperationType">
		<xsd:sequence>
			<xsd:element name="LocalizedName" type="tns:LocalizedDescriptionType"
				minOccurs="1" maxOccurs="unbounded" />
			<xsd:element name="LocalizedDescription" type="tns:LocalizedDescriptionType"
				maxOccurs="unbounded" minOccurs="1" />
			<xsd:element name="OperationParameter" type="tns:OperationParameterType"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="id" type="tns:StrId" use="required" />
		<xsd:attribute name="actionURL" type="tns:Str255" use="required" />
	</xsd:complexType>

	<xsd:complexType name="OperationParameterType">
		<xsd:sequence>
			<xsd:element name="LocalizedName" type="tns:LocalizedDescriptionType"
				minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="id" type="tns:StrId" use="required" />
		<xsd:attribute name="type" type="tns:OperationParameterTypeType"
			use="required" />
		<xsd:attribute name="mandatory" type="xsd:boolean"
			default="false" />
	</xsd:complexType>

	<xsd:simpleType name="OperationParameterTypeType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="INPUT_STRING" />
			<xsd:enumeration value="REQUEST_SELECT" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="CustomTabName">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="locale" type="xsd:string" />
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:complexType name="CustomTabUrl">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="locale" type="xsd:string" />
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

</xsd:schema>

=== servicecatalog/development/oscm-converter-unittests/javares/TechnicalServiceCurrent.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright FUJITSU LIMITED 2017-->
 
<tns:TechnicalServices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="oscm.serviceprovisioning/1.9/TechnicalService.xsd ../../oscm-serviceprovisioning/javares/TechnicalServices.xsd"
  xmlns:tns="oscm.serviceprovisioning/1.9/TechnicalService.xsd">

  <tns:TechnicalService accessType="DIRECT" allowingOnBehalfActing="false" baseUrl=""
    build="2014-02-20" id="LPLATFORM" loginPath="/Dynamically provided by the IaaS-system"
    onlyOneSubscriptionPerUser="false" provisioningType="ASYNCHRONOUS"
    provisioningUrl="https://localhost:8081/oscm-app/webservices/oscm-app/oscm-app/org.oscm.app.v2_0.service.AsynchronousProvisioningProxy?wsdl" provisioningVersion="1.0" billingIdentifier="NATIVE_BILLING">

    <AccessInfo locale="en" >Description of how to access the application.</AccessInfo>
    <AccessInfo locale="ja" />
    <LocalizedDescription locale="en">ROR IaaS implementation.</LocalizedDescription>
    <LocalizedDescription locale="ja">ROR IaaS の実装</LocalizedDescription>
    <LocalizedLicense locale="en" />
    <LocalizedLicense locale="ja" />
    <LocalizedTag locale="en">private cloud</LocalizedTag>
    <LocalizedTag locale="en">windows</LocalizedTag>
    <LocalizedTag locale="en">centos</LocalizedTag>
    <LocalizedTag locale="en">fujitsu cloud</LocalizedTag>
    <LocalizedTag locale="en">ror</LocalizedTag>
    <LocalizedTag locale="ja">プライベート・クラウド</LocalizedTag>
    <LocalizedTag locale="ja">windows</LocalizedTag>
    <LocalizedTag locale="ja">centos</LocalizedTag>
    <LocalizedTag locale="ja">富士通クラウド</LocalizedTag>
    <LocalizedTag locale="ja">ror</LocalizedTag>

    <ParameterDefinition configurable="false" default="ess.ror" id="APP_CONTROLLER_ID" mandatory="true"
      valueType="STRING">
      <LocalizedDescription locale="en">The ID of the APP sample service controller.</LocalizedDescription>
      <LocalizedDescription locale="ja">APPサンプル・サービス・コントローラーのID</LocalizedDescription>
    </ParameterDefinition>

    <ParameterDefinition configurable="true" default="ror([a-z0-9]){2,25}" id="INSTANCENAME_PATTERN"
      mandatory="true" valueType="STRING">
      <LocalizedDescription locale="en">Validation pattern for instance names (regex)</LocalizedDescription>
      <LocalizedDescription locale="ja">インスタンスの名前の妥当性を検証するためのパターン (正規表現)</LocalizedDescription>
    </ParameterDefinition>

    <ParameterDefinition configurable="true" default="ror" id="INSTANCENAME_PREFIX" mandatory="false"
      valueType="STRING">
      <LocalizedDescription locale="en">Prefix for the instance names (prepended automatically)</LocalizedDescription>
      <LocalizedDescription locale="ja">インスタンス名のプレフィックス (自動的に先頭に追加されます)</LocalizedDescription>
    </ParameterDefinition>

    <ParameterDefinition configurable="true" id="INSTANCENAME" mandatory="true" valueType="STRING">
      <LocalizedDescription locale="en">Virtual System Instance Name</LocalizedDescription>
      <LocalizedDescription locale="ja">仮想システムのインスタンス名</LocalizedDescription>
    </ParameterDefinition>

    <ParameterDefinition configurable="true" default="template-13c8ab3348d" id="SYSTEM_TEMPLATE_ID"
      mandatory="true" valueType="STRING">
      <LocalizedDescription locale="en">Virtual System Template ID</LocalizedDescription>
      <LocalizedDescription locale="ja">仮想システムのテンプレートID</LocalizedDescription>
    </ParameterDefinition>

    <ParameterDefinition configurable="true" default="image-13cedeaf7ed" id="MASTER_TEMPLATE_ID"
      mandatory="true" valueType="STRING">
      <LocalizedDescription locale="en">Master Virtual Server Image ID</LocalizedDescription>
      <LocalizedDescription locale="ja">マスター仮想サーバのイメージID</LocalizedDescription>
    </ParameterDefinition>

    <ParameterDefinition configurable="true" default="image-13c8a812d25" id="SLAVE_TEMPLATE_ID"
      mandatory="true" valueType="STRING">
      <LocalizedDescription locale="en">Slave Virtual Server Image ID</LocalizedDescription>
      <LocalizedDescription locale="ja">スレーブ仮想サーバのイメージID</LocalizedDescription>
    </ParameterDefinition>

    <ParameterDefinition configurable="true" default="2" id="CLUSTER_SIZE" mandatory="true"
      valueType="ENUMERATION">
      <Options>
        <Option id="2">
          <LocalizedOption locale="en">Minimum cluster (2-VM)</LocalizedOption>
          <LocalizedOption locale="ja">小規模のクラスター構成 (2 VM)</LocalizedOption>
        </Option>
        <Option id="4">
          <LocalizedOption locale="en">Medium cluster (4-VM)</LocalizedOption>
          <LocalizedOption locale="ja">中規模のクラスター構成 (4 VM)</LocalizedOption>
        </Option>
        <Option id="6">
          <LocalizedOption locale="en">Maximum cluster (6-VM)</LocalizedOption>
          <LocalizedOption locale="ja">大規模のクラスター構成 (6 VM)</LocalizedOption>
        </Option>
      </Options>
      <LocalizedDescription locale="en">Cluster Size</LocalizedDescription>
      <LocalizedDescription locale="ja">クラスターの規模</LocalizedDescription>
    </ParameterDefinition>

    <ParameterDefinition configurable="true" default="1" id="COUNT_CPU" mandatory="false" valueType="ENUMERATION">
      <Options>
        <Option id="1">
          <LocalizedOption locale="en">1-CPU</LocalizedOption>
          <LocalizedOption locale="ja">1個</LocalizedOption>
        </Option>
        <Option id="2">
          <LocalizedOption locale="en">2-CPU</LocalizedOption>
          <LocalizedOption locale="ja">2個</LocalizedOption>
        </Option>
        <Option id="4">
          <LocalizedOption locale="en">4-CPU</LocalizedOption>
          <LocalizedOption locale="ja">4個</LocalizedOption>
        </Option>
      </Options>
      <LocalizedDescription locale="en">CPU Count</LocalizedDescription>
      <LocalizedDescription locale="ja">CPU数</LocalizedDescription>
    </ParameterDefinition>

    <ParameterDefinition configurable="false" default="somebody@web.de" id="MAIL_FOR_COMPLETION"
      mandatory="false" valueType="STRING">
      <LocalizedDescription locale="en">The address to which emails are to be sent that describe manual steps required to complete an operation. If you specify this parameter, the service controller interrupts the processing of each operation before its completion and waits for a notification about the execution of a manual action. Omit this parameter if you do not want to interrupt the processing.</LocalizedDescription>
      <LocalizedDescription locale="ja">操作を完了するために手動の手順が必要であることを知らせるemailの送信先メールアドレス。このパラメーターを指定すると、サービスコントロールは各操作の完了前に処理を中断して、手動の操作が終わったことを知らせる通知が届くまで待ちます。処理を中断したくない場合は、このパラメーターを省略してください。</LocalizedDescription>
    </ParameterDefinition>

    <ParameterDefinition configurable="true" default="somebody@web.de" id="MAIL_FOR_NOTIFICATION"
      mandatory="false" valueType="STRING">
      <LocalizedDescription locale="en">The address to which emails are to be sent that notify service users or administrators of customer organizations about a successful modification of a virtual platform or server. Such modifications result from changes in the configuration parameters at a corresponding subscription.</LocalizedDescription>
      <LocalizedDescription locale="ja">仮想プラットフォームまたはサーバの更新に成功したことを知らせるemailの送信先メールアドレス。サービスの利用者またはサービス利用部門の管理者のメールアドレスを指定します。対応する購入済サービスのサービス設定のパラメータを変更したときに、仮想プラットフォームやサーバが更新されます。</LocalizedDescription>
    </ParameterDefinition>
    <Operation actionURL="https://localhost:8081/oscm-app/webservices/oscm-app/oscm-app/org.oscm.app.v2_0.service.AsynchronousOperationProxy?wsdl" id="START_VIRTUAL_SYSTEM">
      <LocalizedName locale="en">Start</LocalizedName>
      <LocalizedName locale="ja">起動</LocalizedName>
      <LocalizedDescription locale="en">Start the system</LocalizedDescription>
      <LocalizedDescription locale="ja">システムを起動します</LocalizedDescription>
    </Operation>
    <Operation actionURL="https://localhost:8081/oscm-app/webservices/oscm-app/oscm-app/org.oscm.app.v2_0.service.AsynchronousOperationProxy?wsdl" id="STOP_VIRTUAL_SYSTEM">
      <LocalizedName locale="en">Stop</LocalizedName>
      <LocalizedName locale="ja">停止</LocalizedName>
      <LocalizedDescription locale="en">Stop the system</LocalizedDescription>
      <LocalizedDescription locale="ja">システムを停止します</LocalizedDescription>
    </Operation>
  </tns:TechnicalService>
</tns:TechnicalServices>

=== servicecatalog/development/oscm-webservices-tests/javares/ROR_VirtualPlatform.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright FUJITSU LIMITED 2017-->
 
<tns:TechnicalServices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="oscm.serviceprovisioning/1.9/TechnicalService.xsd ../../oscm-serviceprovisioning/javares/TechnicalServices.xsd"
  xmlns:tns="oscm.serviceprovisioning/1.9/TechnicalService.xsd">

  <tns:TechnicalService accessType="DIRECT" allowingOnBehalfActing="false" baseUrl="not_required"
    build="26.03.2013" id="ROR_VirtualPlatform" loginPath="/Dynamically provided by the IaaS-system"
    onlyOneSubscriptionPerUser="false" provisioningType="ASYNCHRONOUS"
    provisioningUrl="^APP_BASE_URL^" provisioningVersion="1.0">

    <AccessInfo locale="en" >Description of how to access the application.</AccessInfo>
    <AccessInfo locale="ja" />
    <LocalizedDescription locale="en">ROR IaaS implementation.</LocalizedDescription>
    <LocalizedDescription locale="ja">ROR IaaS の実装</LocalizedDescription>
    <LocalizedLicense locale="en" />
    <LocalizedLicense locale="ja" />
    <LocalizedTag locale="en">private cloud</LocalizedTag>
    <LocalizedTag locale="en">windows</LocalizedTag>
    <LocalizedTag locale="en">centos</LocalizedTag>
    <LocalizedTag locale="en">fujitsu cloud</LocalizedTag>
    <LocalizedTag locale="en">ror</LocalizedTag>
    <LocalizedTag locale="ja">プライベート・クラウド</LocalizedTag>
    <LocalizedTag locale="ja">windows</LocalizedTag>
    <LocalizedTag locale="ja">centos</LocalizedTag>
    <LocalizedTag locale="ja">富士通クラウド</LocalizedTag>
    <LocalizedTag locale="ja">ror</LocalizedTag>

    <ParameterDefinition configurable="false" default="ess.ror" id="APP_CONTROLLER_ID" mandatory="true"
      valueType="STRING">
      <LocalizedDescription locale="en">The ID of the APP sample service controller.</LocalizedDescription>
      <LocalizedDescription locale="ja">APPサンプル・サービス・コントローラーのID</LocalizedDescription>
    </ParameterDefinition>

    <ParameterDefinition configurable="false" default="^userKey^" id="APP_BSS_USER" mandatory="true"
      valueType="STRING">
      <LocalizedDescription locale="en">The user key of the technology manager to be used for service calls to
        OSCM.</LocalizedDescription>
      <LocalizedDescription locale="ja">OSCMのサービスを呼び出す際に利用する技術サービス管理者の利用者キー</LocalizedDescription>
    </ParameterDefinition>

    <ParameterDefinition configurable="false" default="secret" id="APP_BSS_USER_PWD" mandatory="true"
      valueType="STRING">
      <LocalizedDescription locale="en">The password of the user to be used for service calls to OSCM</LocalizedDescription>
      <LocalizedDescription locale="ja">OSCMのサービスを呼び出す際に利用する利用者のパスワード</LocalizedDescription>
    </ParameterDefinition>

    <ParameterDefinition configurable="true" default="ror([a-z0-9]){2,25}" id="INSTANCENAME_PATTERN"
      mandatory="true" valueType="STRING">
      <LocalizedDescription locale="en">Validation pattern for instance names (regex)</LocalizedDescription>
      <LocalizedDescription locale="ja">インスタンスの名前の妥当性を検証するためのパターン (正規表現)</LocalizedDescription>
    </ParameterDefinition>

    <ParameterDefinition configurable="true" default="ror" id="INSTANCENAME_PREFIX" mandatory="false"
      valueType="STRING">
      <LocalizedDescription locale="en">Prefix for the instance names (prepended automatically)</LocalizedDescription>
      <LocalizedDescription locale="ja">インスタンス名のプレフィックス (自動的に先頭に追加されます)</LocalizedDescription>
    </ParameterDefinition>

    <ParameterDefinition configurable="true" id="INSTANCENAME" mandatory="true" valueType="STRING">
      <LocalizedDescription locale="en">Virtual System Instance Name</LocalizedDescription>
      <LocalizedDescription locale="ja">仮想システムのインスタンス名</LocalizedDescription>
    </ParameterDefinition>

    <ParameterDefinition configurable="true" default="template-13c8ab3348d" id="SYSTEM_TEMPLATE_ID"
      mandatory="true" valueType="STRING">
      <LocalizedDescription locale="en">Virtual System Template ID</LocalizedDescription>
      <LocalizedDescription locale="ja">仮想システムのテンプレートID</LocalizedDescription>
    </ParameterDefinition>

    <ParameterDefinition configurable="true" default="image-13cedeaf7ed" id="MASTER_TEMPLATE_ID"
      mandatory="true" valueType="STRING">
      <LocalizedDescription locale="en">Master Virtual Server Template ID</LocalizedDescription>
      <LocalizedDescription locale="ja">マスター仮想サーバのテンプレートID</LocalizedDescription>
    </ParameterDefinition>

    <ParameterDefinition configurable="true" default="image-13c8a812d25" id="SLAVE_TEMPLATE_ID"
      mandatory="true" valueType="STRING">
      <LocalizedDescription locale="en">Slave Virtual Server Template ID</LocalizedDescription>
      <LocalizedDescription locale="ja">スレーブ仮想サーバのテンプレートID</LocalizedDescription>
    </ParameterDefinition>

    <ParameterDefinition configurable="true" default="2" id="CLUSTER_SIZE" mandatory="true"
      valueType="ENUMERATION">
      <Options>
        <Option id="2">
          <LocalizedOption locale="en">Minimum cluster (2-VM)</LocalizedOption>
          <LocalizedOption locale="ja">小規模のクラスター構成 (2 VM)</LocalizedOption>
        </Option>
        <Option id="4">
          <LocalizedOption locale="en">Medium cluster (4-VM)</LocalizedOption>
          <LocalizedOption locale="ja">中規模のクラスター構成 (4 VM)</LocalizedOption>
        </Option>
        <Option id="9">
          <LocalizedOption locale="en">Maximum cluster (9-VM)</LocalizedOption>
          <LocalizedOption locale="ja">大規模のクラスター構成 (9 VM)</LocalizedOption>
        </Option>
      </Options>
      <LocalizedDescription locale="en">Cluster Size</LocalizedDescription>
      <LocalizedDescription locale="ja">クラスターの規模</LocalizedDescription>
    </ParameterDefinition>

    <ParameterDefinition configurable="true" default="1" id="COUNT_CPU" mandatory="false" valueType="ENUMERATION">
      <Options>
        <Option id="1">
          <LocalizedOption locale="en">1-CPU</LocalizedOption>
          <LocalizedOption locale="ja">1個</LocalizedOption>
        </Option>
        <Option id="2">
          <LocalizedOption locale="en">2-CPU</LocalizedOption>
          <LocalizedOption locale="ja">2個</LocalizedOption>
        </Option>
        <Option id="4">
          <LocalizedOption locale="en">4-CPU</LocalizedOption>
          <LocalizedOption locale="ja">4個</LocalizedOption>
        </Option>
      </Options>
      <LocalizedDescription locale="en">CPU Count</LocalizedDescription>
      <LocalizedDescription locale="ja">CPU数</LocalizedDescription>
    </ParameterDefinition>

    <ParameterDefinition configurable="true" default="^mail.username^" id="MAIL_FOR_COMPLETION"
      mandatory="false" valueType="STRING">
      <LocalizedDescription locale="en">The address to which emails are to be sent that describe manual steps required to complete an operation. If you specify this parameter, the service controller interrupts the processing of each operation before its completion and waits for a notification about the execution of a manual action. Omit this parameter if you do not want to interrupt the processing.</LocalizedDescription>
      <LocalizedDescription locale="ja">操作を完了するために手動の手順が必要であることを知らせるemailの送信先メールアドレス。このパラメーターを指定すると、サービスコントロールは各操作の完了前に処理を中断して、手動の操作が終わったことを知らせる通知が届くまで待ちます。処理を中断したくない場合は、このパラメーターを省略してください。</LocalizedDescription>
    </ParameterDefinition>

    <ParameterDefinition configurable="true" default="^mail.username^" id="MAIL_FOR_NOTIFICATION"
      mandatory="false" valueType="STRING">
      <LocalizedDescription locale="en">The address to which emails are to be sent that notify service users or administrators of customer organizations about a successful modification of a virtual platform or server. Such modifications result from changes in the configuration parameters at a corresponding subscription.</LocalizedDescription>
      <LocalizedDescription locale="ja">仮想プラットフォームまたはサーバの更新に成功したことを知らせるemailの送信先メールアドレス。サービスの利用者またはサービス利用部門の管理者のメールアドレスを指定します。対応する購入済サービスのサービス設定のパラメータを変更したときに、仮想プラットフォームやサーバが更新されます。</LocalizedDescription>
    </ParameterDefinition>
  </tns:TechnicalService>
</tns:TechnicalServices>
