=== servicecatalog/development/oscm-serviceprovisioning/javares/TechnicalServices.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="oscm.serviceprovisioning/1.9/TechnicalService.xsd"
	xmlns:tns="oscm.serviceprovisioning/1.9/TechnicalService.xsd">

	<xsd:element name="TechnicalServices">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="tns:TechnicalService" maxOccurs="unbounded"
					minOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="TechnicalService">
		<xsd:complexType>

			<xsd:sequence>
				<xsd:element name="AccessInfo" type="tns:LocalizedDescriptionType"
					maxOccurs="unbounded" minOccurs="0" />
				<xsd:element name="LocalizedDescription" type="tns:LocalizedDescriptionType"
					maxOccurs="unbounded" minOccurs="0" />
				<xsd:element name="LocalizedLicense" type="tns:LocalizedDescriptionType"
					maxOccurs="unbounded" minOccurs="0" />
				<xsd:element name="LocalizedTag" type="tns:LocalizedDescriptionType"
					maxOccurs="unbounded" minOccurs="0" />
				<xsd:element name="ParameterDefinition" type="tns:ParameterDefinitionType"
					maxOccurs="unbounded" minOccurs="0" />
				<xsd:element name="Event" type="tns:EventType"
					maxOccurs="unbounded" minOccurs="0" />
				<xsd:element name="Role" type="tns:RoleType" maxOccurs="unbounded"
					minOccurs="0" />
				<xsd:element name="Operation" type="tns:OperationType"
					minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>

			<xsd:attribute name="id" type="tns:StrId" use="required" />
			<xsd:attribute name="build" type="tns:Str255" />
			<xsd:attribute name="accessType" use="required">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="DIRECT" />
						<xsd:enumeration value="LOGIN" />
						<xsd:enumeration value="USER" />
						<xsd:enumeration value="EXTERNAL" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>

			<xsd:attribute name="provisioningType">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="ASYNCHRONOUS" />
						<xsd:enumeration value="SYNCHRONOUS" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>

			<xsd:attribute name="provisioningUrl" type="tns:Str255" />
			<xsd:attribute name="provisioningVersion" type="tns:Str255" />
			<xsd:attribute name="provisioningTimeout" type="xsd:long" />
			<xsd:attribute name="provisioningUsername" type="tns:Str255" />
			<xsd:attribute name="provisioningPassword" type="tns:Str255" />
			<xsd:attribute name="baseUrl" type="tns:Str255" />
			<xsd:attribute name="loginPath" type="tns:Str255" />
			<xsd:attribute name="onlyOneSubscriptionPerUser" type="xsd:boolean"
				default="false" />
			<xsd:attribute name="allowingOnBehalfActing" type="xsd:boolean"
				default="false" />
			<xsd:attribute name="billingIdentifier" type="tns:Str255" />
		</xsd:complexType>
	</xsd:element>

	<xsd:simpleType name="StrId">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="40" />
			<xsd:pattern
				value="[()\-.0-9@A-Z\[\]_a-&#xD7FF;&#xE000;-&#xFFFD;&#x10000;-&#x10FFFF;]+([&#x20;]*[()\-.0-9@A-Z\[\]_a-&#xD7FF;&#xE000;-&#xFFFD;&#x10000;-&#x10FFFF;])*" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="Str255">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="255" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="LocalizedDescriptionType">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="locale" type="xsd:string" />
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:complexType name="EventType">
		<xsd:sequence>
			<xsd:element name="LocalizedDescription" type="tns:LocalizedDescriptionType"
				maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="id" type="tns:StrId" use="required" />
	</xsd:complexType>

	<xsd:complexType name="RoleType">
		<xsd:sequence>
			<xsd:element name="LocalizedName" type="tns:LocalizedDescriptionType"
				maxOccurs="unbounded" minOccurs="1" />
			<xsd:element name="LocalizedDescription" type="tns:LocalizedDescriptionType"
				maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="id" type="tns:StrId" use="required" />
	</xsd:complexType>

	<xsd:complexType name="ParameterDefinitionType">
		<xsd:sequence>
			<xsd:element name="Options" type="tns:OptionsType"
				maxOccurs="1" minOccurs="0" />
			<xsd:element name="LocalizedDescription" type="tns:LocalizedDescriptionType"
				maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="id" type="tns:StrId" use="required" />
		<xsd:attribute name="mandatory" type="xsd:boolean" use="optional" />
		<xsd:attribute name="configurable" type="xsd:boolean"
			use="optional" />
		<xsd:attribute name="default" type="xsd:string" use="optional" />
		<xsd:attribute name="minValue" type="xsd:long" use="optional" />
		<xsd:attribute name="maxValue" type="xsd:long" use="optional" />
		<xsd:attribute name="valueType" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="BOOLEAN" />
					<xsd:enumeration value="INTEGER" />
					<xsd:enumeration value="LONG" />
					<xsd:enumeration value="STRING" />
					<xsd:enumeration value="ENUMERATION" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="modificationType" use="optional"
			default="STANDARD">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="STANDARD" />
					<xsd:enumeration value="ONE_TIME" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="OptionsType">
		<xsd:sequence>
			<xsd:element name="Option" type="tns:OptionType"
				maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="OptionType">
		<xsd:sequence>
			<xsd:element name="LocalizedOption" type="tns:LocalizedDescriptionType"
				maxOccurs="unbounded" minOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="id" type="tns:StrId" use="required" />
	</xsd:complexType>

	<xsd:complexType name="OperationType">
		<xsd:sequence>
			<xsd:element name="LocalizedName" type="tns:LocalizedDescriptionType"
				minOccurs="1" maxOccurs="unbounded" />
			<xsd:element name="LocalizedDescription" type="tns:LocalizedDescriptionType"
				maxOccurs="unbounded" minOccurs="1" />
			<xsd:element name="OperationParameter" type="tns:OperationParameterType"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="id" type="tns:StrId" use="required" />
		<xsd:attribute name="actionURL" type="tns:Str255" use="required" />
	</xsd:complexType>

	<xsd:complexType name="OperationParameterType">
		<xsd:sequence>
			<xsd:element name="LocalizedName" type="tns:LocalizedDescriptionType"
				minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="id" type="tns:StrId" use="required" />
		<xsd:attribute name="type" type="tns:OperationParameterTypeType"
			use="required" />
		<xsd:attribute name="mandatory" type="xsd:boolean"
			default="false" />
	</xsd:complexType>

	<xsd:simpleType name="OperationParameterTypeType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="INPUT_STRING" />
			<xsd:enumeration value="REQUEST_SELECT" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="CustomTabName">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="locale" type="xsd:string" />
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:complexType name="CustomTabUrl">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="locale" type="xsd:string" />
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

</xsd:schema>

=== servicecatalog/development/oscm-app-aws/resources/TechnicalService_AWS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright FUJITSU LIMITED 2017-->

<tns:TechnicalServices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="oscm.serviceprovisioning/1.9/TechnicalService.xsd ../../oscm-serviceprovisioning/javares/TechnicalServices.xsd"
	xmlns:tns="oscm.serviceprovisioning/1.9/TechnicalService.xsd">

	<tns:TechnicalService accessType="DIRECT"
		allowingOnBehalfActing="false" baseUrl="" build="2014-06-11" id="AWS_EC2"
		loginPath="/Dynamically provided by the IaaS-system"
		onlyOneSubscriptionPerUser="false" provisioningType="ASYNCHRONOUS"
		provisioningUrl="http://oscm-app:8880/oscm-app/webservices/oscm-app/oscm-app/org.oscm.app.v2_0.service.AsynchronousProvisioningProxy?wsdl"
		provisioningVersion="1.0">
		<AccessInfo locale="en">AWS Access Info. </AccessInfo>
		<LocalizedDescription locale="de">AWS EC2 Provisioning</LocalizedDescription>
		<LocalizedDescription locale="en">AWS EC2 Provisioning</LocalizedDescription>
		<LocalizedLicense locale="en" />
		<ParameterDefinition configurable="false" default="ess.aws"
			id="APP_CONTROLLER_ID" mandatory="true" valueType="STRING">
			<LocalizedDescription locale="en">The ID of the APP controller implementation.</LocalizedDescription>
		</ParameterDefinition>
		<ParameterDefinition configurable="true"
			default="aws([a-z0-9]){2,32}" id="INSTANCENAME_PATTERN"
			modificationType="ONE_TIME" mandatory="true" valueType="STRING">
			<LocalizedDescription locale="en">Validation pattern for instance name (regex)</LocalizedDescription>
		</ParameterDefinition>
		<ParameterDefinition configurable="true" default="aws"
			id="INSTANCENAME_PREFIX" mandatory="false" modificationType="ONE_TIME"
			valueType="STRING">
			<LocalizedDescription locale="en">Automatically prepended prefix for the instance name</LocalizedDescription>
		</ParameterDefinition>
		<ParameterDefinition configurable="true" id="INSTANCENAME"
			mandatory="true" modificationType="ONE_TIME" valueType="STRING">
			<LocalizedDescription locale="de">Instanz-Name des virtuellen Systems</LocalizedDescription>
			<LocalizedDescription locale="en">Virtual System Instance Name</LocalizedDescription>
		</ParameterDefinition>
		<ParameterDefinition configurable="true" id="KEY_PAIR_NAME"
			mandatory="true" modificationType="ONE_TIME" valueType="STRING">
			<LocalizedDescription locale="de">Der Key Pair-Name definiert den privaten Schlüssel, der den
        Zugriff auf die Instanz erhält</LocalizedDescription>
			<LocalizedDescription locale="en">The key pair name defines the private key that can be used to
        access the instance</LocalizedDescription>
		</ParameterDefinition>
		<ParameterDefinition configurable="true" default="ami-0d77397e"
			id="IMAGE_NAME" modificationType="ONE_TIME" mandatory="true"
			valueType="STRING">
			<LocalizedDescription locale="de">Name des AMI</LocalizedDescription>
			<LocalizedDescription locale="en">Name of AMI</LocalizedDescription>
		</ParameterDefinition>
		<ParameterDefinition configurable="true" default="t2.micro"
			id="INSTANCE_TYPE" mandatory="true" modificationType="ONE_TIME"
			valueType="ENUMERATION">
			<Options>
				<Option id="t1.micro">
					<LocalizedOption locale="en">t1.micro</LocalizedOption>
				</Option>
				<Option id="t2.micro">
					<LocalizedOption locale="en">t2.micro</LocalizedOption>
				</Option>
				<Option id="m1.small">
					<LocalizedOption locale="en">m1.small</LocalizedOption>
				</Option>
				<Option id="m1.medium">
					<LocalizedOption locale="en">m3.medium</LocalizedOption>
				</Option>
			</Options>
			<LocalizedDescription locale="de">Instance-Typ</LocalizedDescription>
			<LocalizedDescription locale="en">Instance Type</LocalizedDescription>
		</ParameterDefinition>
		<ParameterDefinition configurable="true" default="eu-west-1"
			id="REGION" mandatory="true" modificationType="ONE_TIME" valueType="ENUMERATION">
			<Options>
				<Option id="us-east-1">
					<LocalizedOption locale="en">US East (Northern Virginia)</LocalizedOption>
				</Option>
				<Option id="us-west-1">
					<LocalizedOption locale="en">US West (Northern California)</LocalizedOption>
				</Option>
				<Option id="us-west-2">
					<LocalizedOption locale="en">US West (Oregon)</LocalizedOption>
				</Option>
				<Option id="eu-west-1">
					<LocalizedOption locale="en">EU (Ireland)</LocalizedOption>
				</Option>
			</Options>
			<LocalizedDescription locale="de">Region</LocalizedDescription>
			<LocalizedDescription locale="en">Region</LocalizedDescription>
		</ParameterDefinition>

		<ParameterDefinition configurable="true"
			default="subnet-a77430d0" id="SUBNET" mandatory="false" valueType="STRING"
			modificationType="ONE_TIME">
			<LocalizedDescription locale="en">Subnet Definition</LocalizedDescription>
			<LocalizedDescription locale="de" />
			<LocalizedDescription locale="ja" />
		</ParameterDefinition>
		<ParameterDefinition configurable="true" default="3"
			id="DISK_SIZE" mandatory="false" minValue="1" maxValue="3" valueType="INTEGER"
			modificationType="ONE_TIME">
			<LocalizedDescription locale="en">Max Disk Size (GB)</LocalizedDescription>
			<LocalizedDescription locale="de" />
			<LocalizedDescription locale="ja" />
		</ParameterDefinition>
		<ParameterDefinition configurable="true" default="true"
			id="PUBLIC_IP" mandatory="false" modificationType="ONE_TIME"
			valueType="BOOLEAN">
			<LocalizedDescription locale="en">Public Ip</LocalizedDescription>
			<LocalizedDescription locale="de" />
			<LocalizedDescription locale="ja" />
		</ParameterDefinition>

		<ParameterDefinition configurable="false" default="<your.mail>"
			id="MAIL_FOR_COMPLETION" mandatory="false" modificationType="ONE_TIME"
			valueType="STRING">
			<LocalizedDescription locale="en">The address to which emails are to be sent that describe manual steps required to complete an operation. If you specify this parameter, the service controller interrupts the processing of each operation before its completion and waits for a notification about the execution of a manual action. Omit this parameter if you do not want to interrupt the processing.</LocalizedDescription>
			<LocalizedDescription locale="ja">操作を完了するために手動の手順が必要であることを知らせるemailの送信先メールアドレス。このパラメーターを指定すると、サービスコントロールは各操作の完了前に処理を中断して、手動の操作が終わったことを知らせる通知が届くまで待ちます。処理を中断したくない場合は、このパラメーターを省略してください。</LocalizedDescription>
		</ParameterDefinition>
		<ParameterDefinition configurable="true" default=""
			id="SECURITY_GROUP_NAMES" mandatory="false" valueType="STRING"
			modificationType="ONE_TIME">
			<LocalizedDescription locale="en">Define security group(s) for the new instance</LocalizedDescription>
		</ParameterDefinition>
		<Operation
			actionURL="http://oscm-app:8880/oscm-app/webservices/oscm-app/oscm-app/org.oscm.app.v2_0.service.AsynchronousOperationProxy?wsdl"
			id="START_VIRTUAL_SYSTEM">
			<LocalizedName locale="de">Start</LocalizedName>
			<LocalizedName locale="en">Start</LocalizedName>
			<LocalizedName locale="ja">起動</LocalizedName>
			<LocalizedDescription locale="de">Startet die Instanz</LocalizedDescription>
			<LocalizedDescription locale="en">Start the instance</LocalizedDescription>
			<LocalizedDescription locale="ja">システムを起動します</LocalizedDescription>
		</Operation>
		<Operation
			actionURL="http://oscm-app:8880/oscm-app/webservices/oscm-app/oscm-app/org.oscm.app.v2_0.service.AsynchronousOperationProxy?wsdl"
			id="STOP_VIRTUAL_SYSTEM">
			<LocalizedName locale="de">Stop</LocalizedName>
			<LocalizedName locale="en">Stop</LocalizedName>
			<LocalizedName locale="ja">停止</LocalizedName>
			<LocalizedDescription locale="de">Stoppt die Instanz</LocalizedDescription>
			<LocalizedDescription locale="en">Stop the instance</LocalizedDescription>
			<LocalizedDescription locale="ja">システムを停止します</LocalizedDescription>
		</Operation>
	</tns:TechnicalService>
</tns:TechnicalServices>
